name: Hello World Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Checkout the repository

      - name: Print Hello World
        run: echo "Hello, World!"  # Prints "Hello, World!" to the console
