jobs:
  frontend-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.modified, 'frontend') || contains(github.event.head_commit.added, 'frontend') || contains(github.event.head_commit.deleted, 'frontend')) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print changed files
        run: echo "Modified files: ${{ github.event.head_commit.modified }}"

      - name: Run frontend specific tasks
        run: echo "Changes detected in frontend. Running frontend job..."

  backend-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.modified, 'backend') || contains(github.event.head_commit.added, 'backend') || contains(github.event.head_commit.deleted, 'backend')) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print changed files
        run: echo "Modified files: ${{ github.event.head_commit.modified }}"

      - name: Run backend specific tasks
        run: echo "Changes detected in backend. Running backend job..."
